search by album name = {u'albums': {u'href': u'https://api.spotify.com/v1/search?query=garden+state+motion+picture&offset=0&limit=10&type=album',
             u'items': [{u'album_type': u'album',
                         u'available_markets': [u'AD',
                                                u'AR',
                                                u'AT',

                                                u'US',
                                                u'UY'],
                         u'external_urls': {u'spotify': u'https://open.spotify.com/album/24mCiOTIF5Ob1uwluRFERv'},
                         u'href': u'https://api.spotify.com/v1/albums/24mCiOTIF5Ob1uwluRFERv',
                         u'id': u'24mCiOTIF5Ob1uwluRFERv',
                         u'images': [{u'height': 640,
                                      u'url': u'https://i.scdn.co/image/1fa26eb1b5435882e283f10407a68490325f7127',
                                      u'width': 640},
                                     {u'height': 300,
                                      u'url': u'https://i.scdn.co/image/c84b114d4fe179def705fb686bbda441692e6446',
                                      u'width': 300},
                                     {u'height': 64,
                                      u'url': u'https://i.scdn.co/image/48628c31595eaf079b35336c47e78c8ff56d22da',
                                      u'width': 64}],
                         u'name': u'Garden State - Music From The Motion Picture',
                         u'type': u'album',
                         u'uri': u'spotify:album:24mCiOTIF5Ob1uwluRFERv'},
                        {u'album_type': u'album',
                         u'available_markets': [u'AD',
                                                u'AR',

                                                u'SV',
                                                u'TR',
                                                u'UY'],
                         u'external_urls': {u'spotify': u'https://open.spotify.com/album/2BC4nAhfuBVnwY50x15Z9m'},
                         u'href': u'https://api.spotify.com/v1/albums/2BC4nAhfuBVnwY50x15Z9m',
                         u'id': u'2BC4nAhfuBVnwY50x15Z9m',
                         u'images': [{u'height': 640,
                                      u'url': u'https://i.scdn.co/image/bc9d9d1141bdf8cd01d3e55810a4c78639be1f2c',
                                      u'width': 640},
                                     {u'height': 300,
                                      u'url': u'https://i.scdn.co/image/b2f4442117bcd68b7841ca9c44d96c868b84166b',
                                      u'width': 300},
                                     {u'height': 64,
                                      u'url': u'https://i.scdn.co/image/ef7b27568a6f3f53471a3b6c04f7494a63ea7df0',
                                      u'width': 64}],
                         u'name': u'Garden State - Music From The Motion Picture',
                         u'type': u'album',
                         u'uri': u'spotify:album:2BC4nAhfuBVnwY50x15Z9m'}],
             u'limit': 10,
             u'next': None,
             u'offset': 0,
             u'previous': None,
             u'total': 2}}






tracklistings by album id = {u'href': u'https://api.spotify.com/v1/albums/24mCiOTIF5Ob1uwluRFERv/tracks?offset=0&limit=50',
 u'items': [{u'artists': [{u'external_urls': {u'spotify': u'https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU'},
                           u'href': u'https://api.spotify.com/v1/artists/4gzpq5DPGxSnKTe4SA8HAU',
                           u'id': u'4gzpq5DPGxSnKTe4SA8HAU',
                           u'name': u'Coldplay',
                           u'type': u'artist',
                           u'uri': u'spotify:artist:4gzpq5DPGxSnKTe4SA8HAU'}],
             u'disc_number': 1,
             u'duration_ms': 136440,
             u'explicit': False,
             u'external_urls': {u'spotify': u'https://open.spotify.com/track/0XoYZSVQjd1hClkZQWYDLk'},
             u'href': u'https://api.spotify.com/v1/tracks/0XoYZSVQjd1hClkZQWYDLk',
             u'id': u'0XoYZSVQjd1hClkZQWYDLk',
             u'name': u"Don't Panic",
             u'preview_url': u'https://p.scdn.co/mp3-preview/6fffe1869ebc8c892c8885ded3fdf43ca0128e92',
             u'track_number': 1,
             u'type': u'track',
             u'uri': u'spotify:track:0XoYZSVQjd1hClkZQWYDLk'},
            {u'artists': [{u'external_urls': {u'spotify': u'https://open.spotify.com/artist/4LG4Bs1Gadht7TCrMytQUO'},
                           u'href': u'https://api.spotify.com/v1/artists/4LG4Bs1Gadht7TCrMytQUO',
                           u'id': u'4LG4Bs1Gadht7TCrMytQUO',
                           u'name': u'The Shins',
                           u'type': u'artist',
                           u'uri': u'spotify:artist:4LG4Bs1Gadht7TCrMytQUO'}],
             u'disc_number': 1,
             u'duration_ms': 199146,
             u'explicit': False,
             u'external_urls': {u'spotify': u'https://open.spotify.com/track/7iTtCJRgOKf5JugoDfrcTg'},
             u'href': u'https://api.spotify.com/v1/tracks/7iTtCJRgOKf5JugoDfrcTg',
             u'id': u'7iTtCJRgOKf5JugoDfrcTg',
             u'name': u'Caring Is Creepy',
             u'preview_url': u'https://p.scdn.co/mp3-preview/f4a3c43b927e9262f031581a7f83826a2353d505',
             u'track_number': 2,
             u'type': u'track',
             u'uri': u'spotify:track:7iTtCJRgOKf5JugoDfrcTg'},
            {u'artists': [{u'external_urls': {u'spotify': u'https://open.spotify.com/artist/14H7ag1wpQOsPPQJOD6Dqr'},
                           u'href': u'https://api.spotify.com/v1/artists/14H7ag1wpQOsPPQJOD6Dqr',
                           u'id': u'14H7ag1wpQOsPPQJOD6Dqr',
                           u'name': u'Zero 7',
                           u'type': u'artist',
                           u'uri': u'spotify:artist:14H7ag1wpQOsPPQJOD6Dqr'}],
             u'disc_number': 1,
             u'duration_ms': 271813,
             u'explicit': False,
             u'external_urls': {u'spotify': u'https://open.spotify.com/track/7Hk60YVg5xbwl2wVnHeBEm'},
             u'href': u'https://api.spotify.com/v1/tracks/7Hk60YVg5xbwl2wVnHeBEm',
             u'id': u'7Hk60YVg5xbwl2wVnHeBEm',
             u'name': u'In the Waiting Line',
             u'preview_url': u'https://p.scdn.co/mp3-preview/5bb1457db8d3c603bb1eaf04f20abf0b80003d49',
             u'track_number': 3,
             u'type': u'track',
             u'uri': u'spotify:track:7Hk60YVg5xbwl2wVnHeBEm'},
            {u'artists': [{u'external_urls': {u'spotify': u'https://open.spotify.com/artist/4LG4Bs1Gadht7TCrMytQUO'},
                           u'href': u'https://api.spotify.com/v1/artists/4LG4Bs1Gadht7TCrMytQUO',
                           u'id': u'4LG4Bs1Gadht7TCrMytQUO',
                           u'name': u'The Shins',
                           u'type': u'artist',
                           u'uri': u'spotify:artist:4LG4Bs1Gadht7TCrMytQUO'}],
             u'disc_number': 1,
             u'duration_ms': 229080,
             u'explicit': False,
             u'external_urls': {u'spotify': u'https://open.spotify.com/track/47F10EemSKAI6A85hLIpn0'},
             u'href': u'https://api.spotify.com/v1/tracks/47F10EemSKAI6A85hLIpn0',
             u'id': u'47F10EemSKAI6A85hLIpn0',
             u'name': u'New Slang',
             u'preview_url': u'https://p.scdn.co/mp3-preview/5c001eba1ed9754ec420b77d39f13a1c48465df7',
             u'track_number': 4,
             u'type': u'track',
             u'uri': u'spotify:track:47F10EemSKAI6A85hLIpn0'},
            {u'artists': [{u'external_urls': {u'spotify': u'https://open.spotify.com/artist/5mxB08ktCukEhGMg2YZeEv'},
                           u'href': u'https://api.spotify.com/v1/artists/5mxB08ktCukEhGMg2YZeEv',
                           u'id': u'5mxB08ktCukEhGMg2YZeEv',
                           u'name': u'Colin Hay',
                           u'type': u'artist',
                           u'uri': u'spotify:artist:5mxB08ktCukEhGMg2YZeEv'}],
             u'disc_number': 1,
             u'duration_ms': 317693,
             u'explicit': False,
             u'external_urls': {u'spotify': u'https://open.spotify.com/track/3wTs7JMHnJWe08vKOZWu7D'},
             u'href': u'https://api.spotify.com/v1/tracks/3wTs7JMHnJWe08vKOZWu7D',
             u'id': u'3wTs7JMHnJWe08vKOZWu7D',
             u'name': u"I Just Don't Think I'll Ever Get Over You",
             u'preview_url': u'https://p.scdn.co/mp3-preview/7c2eb9335c6bb154fe752b370cd5f67d5cf8b4ee',
             u'track_number': 5,
             u'type': u'track',
             u'uri': u'spotify:track:3wTs7JMHnJWe08vKOZWu7D'},
            {u'artists': [{u'external_urls': {u'spotify': u'https://open.spotify.com/artist/21R50WhyQI5HxWOTr6MyY1'},
                           u'href': u'https://api.spotify.com/v1/artists/21R50WhyQI5HxWOTr6MyY1',
                           u'id': u'21R50WhyQI5HxWOTr6MyY1',
                           u'name': u'Cary Brothers',
                           u'type': u'artist',
                           u'uri': u'spotify:artist:21R50WhyQI5HxWOTr6MyY1'}],
             u'disc_number': 1,
             u'duration_ms': 257440,
             u'explicit': False,
             u'external_urls': {u'spotify': u'https://open.spotify.com/track/65j467erWjqP4wP5KfG9US'},
             u'href': u'https://api.spotify.com/v1/tracks/65j467erWjqP4wP5KfG9US',
             u'id': u'65j467erWjqP4wP5KfG9US',
             u'name': u'Blue Eyes',
             u'preview_url': u'https://p.scdn.co/mp3-preview/6ef622c2a8f41cbe4401a68973a78625bea75c13',
             u'track_number': 6,
             u'type': u'track',
             u'uri': u'spotify:track:65j467erWjqP4wP5KfG9US'},
            {u'artists': [{u'external_urls': {u'spotify': u'https://open.spotify.com/artist/2pZCKLhbrrDD4PwEzrDig3'},
                           u'href': u'https://api.spotify.com/v1/artists/2pZCKLhbrrDD4PwEzrDig3',
                           u'id': u'2pZCKLhbrrDD4PwEzrDig3',
                           u'name': u'Remy Zero',
                           u'type': u'artist',
                           u'uri': u'spotify:artist:2pZCKLhbrrDD4PwEzrDig3'}],
             u'disc_number': 1,
             u'duration_ms': 233746,
             u'explicit': False,
             u'external_urls': {u'spotify': u'https://open.spotify.com/track/2XKCbCew4NX5sUZCQs9uWi'},
             u'href': u'https://api.spotify.com/v1/tracks/2XKCbCew4NX5sUZCQs9uWi',
             u'id': u'2XKCbCew4NX5sUZCQs9uWi',
             u'name': u'Fair',
             u'preview_url': u'https://p.scdn.co/mp3-preview/d58d17ff7a735611f8aefb2910fb3a74e5c0d336',
             u'track_number': 7,
             u'type': u'track',
             u'uri': u'spotify:track:2XKCbCew4NX5sUZCQs9uWi'},
            {u'artists': [{u'external_urls': {u'spotify': u'https://open.spotify.com/artist/5c3GLXai8YOMid29ZEuR9y'},
                           u'href': u'https://api.spotify.com/v1/artists/5c3GLXai8YOMid29ZEuR9y',
                           u'id': u'5c3GLXai8YOMid29ZEuR9y',
                           u'name': u'Nick Drake',
                           u'type': u'artist',
                           u'uri': u'spotify:artist:5c3GLXai8YOMid29ZEuR9y'}],
             u'disc_number': 1,
             u'duration_ms': 288866,
             u'explicit': False,
             u'external_urls': {u'spotify': u'https://open.spotify.com/track/5iJxxPSkOZfvFfVqob3UP7'},
             u'href': u'https://api.spotify.com/v1/tracks/5iJxxPSkOZfvFfVqob3UP7',
             u'id': u'5iJxxPSkOZfvFfVqob3UP7',
             u'name': u'One Of These Things First',
             u'preview_url': u'https://p.scdn.co/mp3-preview/8f492b3f9d14d56e734b83890c0376fb29ea0736',
             u'track_number': 8,
             u'type': u'track',
             u'uri': u'spotify:track:5iJxxPSkOZfvFfVqob3UP7'},
            {u'artists': [{u'external_urls': {u'spotify': u'https://open.spotify.com/artist/25KNo5GDS6ZpLkjasaecA3'},
                           u'href': u'https://api.spotify.com/v1/artists/25KNo5GDS6ZpLkjasaecA3',
                           u'id': u'25KNo5GDS6ZpLkjasaecA3',
                           u'name': u'Thievery Corporation',
                           u'type': u'artist',
                           u'uri': u'spotify:artist:25KNo5GDS6ZpLkjasaecA3'}],
             u'disc_number': 1,
             u'duration_ms': 286480,
             u'explicit': False,
             u'external_urls': {u'spotify': u'https://open.spotify.com/track/0LQW3QOPjECHV9y8y47OOT'},
             u'href': u'https://api.spotify.com/v1/tracks/0LQW3QOPjECHV9y8y47OOT',
             u'id': u'0LQW3QOPjECHV9y8y47OOT',
             u'name': u'Lebanese Blonde',
             u'preview_url': u'https://p.scdn.co/mp3-preview/d5ba2e2f78642237e093897fe222b03e87e9f611',
             u'track_number': 9,
             u'type': u'track',
             u'uri': u'spotify:track:0LQW3QOPjECHV9y8y47OOT'},
            {u'artists': [{u'external_urls': {u'spotify': u'https://open.spotify.com/artist/70cRZdQywnSFp9pnc2WTCE'},
                           u'href': u'https://api.spotify.com/v1/artists/70cRZdQywnSFp9pnc2WTCE',
                           u'id': u'70cRZdQywnSFp9pnc2WTCE',
                           u'name': u'Simon & Garfunkel',
                           u'type': u'artist',
                           u'uri': u'spotify:artist:70cRZdQywnSFp9pnc2WTCE'}],
             u'disc_number': 1,
             u'duration_ms': 237373,
             u'explicit': False,
             u'external_urls': {u'spotify': u'https://open.spotify.com/track/5h6GtBMMb29l3EsbegykTD'},
             u'href': u'https://api.spotify.com/v1/tracks/5h6GtBMMb29l3EsbegykTD',
             u'id': u'5h6GtBMMb29l3EsbegykTD',
             u'name': u'The Only Living Boy in New York',
             u'preview_url': u'https://p.scdn.co/mp3-preview/04c13c488e8dd35d6676d5e1b9673c3d23f1acd5',
             u'track_number': 10,
             u'type': u'track',
             u'uri': u'spotify:track:5h6GtBMMb29l3EsbegykTD'},
            {u'artists': [{u'external_urls': {u'spotify': u'https://open.spotify.com/artist/4M5nCE77Qaxayuhp3fVn4V'},
                           u'href': u'https://api.spotify.com/v1/artists/4M5nCE77Qaxayuhp3fVn4V',
                           u'id': u'4M5nCE77Qaxayuhp3fVn4V',
                           u'name': u'Iron & Wine',
                           u'type': u'artist',
                           u'uri': u'spotify:artist:4M5nCE77Qaxayuhp3fVn4V'}],
             u'disc_number': 1,
             u'duration_ms': 250520,
             u'explicit': False,
             u'external_urls': {u'spotify': u'https://open.spotify.com/track/0FE4fV98h1lXMSbJXdRxbV'},
             u'href': u'https://api.spotify.com/v1/tracks/0FE4fV98h1lXMSbJXdRxbV',
             u'id': u'0FE4fV98h1lXMSbJXdRxbV',
             u'name': u'Such Great Heights',
             u'preview_url': u'https://p.scdn.co/mp3-preview/58ba43ed8c5b8008551367900924b9d2bcbce37d',
             u'track_number': 11,
             u'type': u'track',
             u'uri': u'spotify:track:0FE4fV98h1lXMSbJXdRxbV'},
            {u'artists': [{u'external_urls': {u'spotify': u'https://open.spotify.com/artist/6MUyqmIQ35inLjch0YzIEG'},
                           u'href': u'https://api.spotify.com/v1/artists/6MUyqmIQ35inLjch0YzIEG',
                           u'id': u'6MUyqmIQ35inLjch0YzIEG',
                           u'name': u'Frou Frou',
                           u'type': u'artist',
                           u'uri': u'spotify:artist:6MUyqmIQ35inLjch0YzIEG'}],
             u'disc_number': 1,
             u'duration_ms': 251640,
             u'explicit': False,
             u'external_urls': {u'spotify': u'https://open.spotify.com/track/0VCQaWo68h62F8VNe1HWCE'},
             u'href': u'https://api.spotify.com/v1/tracks/0VCQaWo68h62F8VNe1HWCE',
             u'id': u'0VCQaWo68h62F8VNe1HWCE',
             u'name': u'Let Go',
             u'preview_url': u'https://p.scdn.co/mp3-preview/4662b8b9596fd6686013f2d8137934545009c148',
             u'track_number': 12,
             u'type': u'track',
             u'uri': u'spotify:track:0VCQaWo68h62F8VNe1HWCE'},
            {u'artists': [{u'external_urls': {u'spotify': u'https://open.spotify.com/artist/61BYG4kCG0bel5KEbDwY0D'},
                           u'href': u'https://api.spotify.com/v1/artists/61BYG4kCG0bel5KEbDwY0D',
                           u'id': u'61BYG4kCG0bel5KEbDwY0D',
                           u'name': u'Bonnie Somerville',
                           u'type': u'artist',
                           u'uri': u'spotify:artist:61BYG4kCG0bel5KEbDwY0D'}],
             u'disc_number': 1,
             u'duration_ms': 207360,
             u'explicit': False,
             u'external_urls': {u'spotify': u'https://open.spotify.com/track/2t74da7Q5jbg2kNQcxeHFP'},
             u'href': u'https://api.spotify.com/v1/tracks/2t74da7Q5jbg2kNQcxeHFP',
             u'id': u'2t74da7Q5jbg2kNQcxeHFP',
             u'name': u'Winding Road',
             u'preview_url': u'https://p.scdn.co/mp3-preview/adecbc6838034e2b11af66852aabe105984d8030',
             u'track_number': 13,
             u'type': u'track',
             u'uri': u'spotify:track:2t74da7Q5jbg2kNQcxeHFP'}],
 u'limit': 50,
 u'next': None,
 u'offset': 0,
 u'previous': None,
 u'total': 13}





